### ISSUE TITLE
Remove dependency on Powershell v3

### ISSUE THREAD

**Issue by nick-o** [rackerlabs/PoSh-Ohai#3]
Currently several parts of the module depend on Powershell version 3 to be installed. Since this is still fairly new and only ships on Server 2012 and later and there are still a lot of Server 2008 and 2008 R2 around it would be beneficial to have PoSh-Ohai work on these as well.

**Comment by hdansou** [comment]
The deployment script is now working on powershell version 2.
https://github.com/rackerlabs/PoSh-Ohai/pull/70
