### ISSUE TITLE
cached data problem

### ISSUE THREAD

**Issue by gusmaskowitz** [rackerlabs/PoSh-Ohai#59]
Today I did a waldo discovery on server "162.242.255.155" to get a baseline. Then I logged into the server and stopped a service (IISLOGS) and set it to Manual not Automatic start. Then rebooted.

Ran a discovery again, but the [system_info][services] dictionary still showed the OLD data from before, not new data. 

I tried this again and again, but the [system_info][services] kept listing the IISLOG service as running, and automatically started.

I think posh-ohai was not actually logging in. 
Please help check.

You are welcome to log into that server. 
It is a managed cloud machine called 'Windows2012' in my account.

Gus

**Comment by hdansou** [comment]
##### Test 1 >>  IISLogs service startup mode is set to Manual and the service is stopped. I compared the service status using the get-service command  with the posh-ohai data(get-computerconfiguration) and we see that the service status is `stopped`.
---
PS C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PoSh-Ohai> $test.services |where {$_.name -eq 'iislogs'}

Name      : IISLogs
ProcessId : 0
State     : Stopped
StartMode : Manual
Status    : OK

PS C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PoSh-Ohai> 
PS C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PoSh-Ohai> Get-Service -Name IISLogs

Status   Name               DisplayName                           
------   ----               -----------                           
Stopped  IISLogs            IISLogs   


##### Test 2 >> I have started the IISLogs service and ran posh-ohai and it displayed the current status of the service, which is `running` on both the get-service and posh-ohai output
----
PS C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PoSh-Ohai> $Test1.services |where {$_.name -eq 'iislogs'}
Name      : IISLogs
ProcessId : 3884
State     : Running
StartMode : Manual
Status    : OK

I think posh-ohai does not have a bug
